[DEFAULT]
IMAGE_FOLDER=/Users/surabhibehera/Documents/Suraj/Projects/Gemma Projects/LiveStreaming/CricScore/Images
RESPONSE_FOLDER=/Users/surabhibehera/Documents/Suraj/Projects/Gemma Projects/LiveStreaming/CricScore/Resposes
MODEL_NAME=gemma3:4b
PROMPT=Give me score and brief commentry of the over and last bowl from this image in json format with keys score and description.
CMTRY_URL=https://www.cricbuzz.com/live-cricket-full-commentary/116774/gaw-vs-snp-25th-match-caribbean-premier-league-2025
INNS=GAW Inns

SCORE_IMAGE_FOLDER=/Users/surabhibehera/Documents/Suraj/Projects/Gemma Projects/LiveStreaming/CricScore/Scores/ScoreImages
SCORE_RESPONSE_FOLDER=/Users/surabhibehera/Documents/Suraj/Projects/Gemma Projects/LiveStreaming/CricScore/Scores/Responses
MODEL_NAME=gemma3:4b
SCORE_PROMPT=Give me score and brief commentry of the over and last bowl from this image in json format with keys score and description.