[DEFAULT]
IMAGE_FOLDER=C:\Projects\CricScoreApp\CricScore\resources\commentry\images
RESPONSE_FOLDER=C:\Projects\CricScoreApp\CricScore\resources\commentry\response
AUDIO_FOLDER=C:\Projects\CricScoreApp\CricScore\resources\commentry\audio
MODEL_NAME=gemma3:4b
PROMPT=Give me score and brief commentry of the over and last bowl from this image in json format with keys score and description.
CMTRY_URL=https://www.cricbuzz.com/live-cricket-full-commentary/116774/gaw-vs-snp-25th-match-caribbean-premier-league-2025
INNS=GAW Inns

SCORE_IMAGE_FOLDER=C:\Projects\CricScoreApp\CricScore\resources\scores\images
SCORE_RESPONSE_FOLDER=C:\Projects\CricScoreApp\CricScore\resources\scores\response
SCORE_PROMPT= sdas
SCORE_URL=https://www.cricbuzz.com/live-cricket-scorecard/116774/gaw-vs-snp-25th-match-caribbean-premier-league-2025
CROP_LEFT=500
CROP_RIGHT=950
CROP_TOP=160
CROP_BOTTOM=400